# to create from scratch: conda env create -f environment.yml
# to update the environment: conda env update --name myenv --file environment.yml --prune
# or update with environment activated: conda env update --file environment.yml --prune

# for exe pyinstaller: install "conda install pywin32" on win machine

name: sp4e-homework3
channels:
    - conda-forge
dependencies:
   - python=3.8
   - pip:
     - matplotlib==3.1.2
   - git